### ISSUE TITLE
Feature: Support recurring crontabs

### ISSUE THREAD

**Issue by sieppl** [jkonieczny/PHP-Crontab#3]
Thanks for the handy script! 

Right now recurring cronttabs like "/10 \* \* \* *" (every ten minutes) are not supported. Would be great to see this feature.

**Comment by matthanley** [comment]
Every ten minutes is supported; the correct cron syntax is
*/10 \* \* \* *

**Comment by sieppl** [comment]
Oops, thanks for the lesson.
